# Generated by Django 5.2.7 on 2025-10-08 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('class_metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='DrawingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_object', models.CharField(max_length=100)),
                ('drawing_data', models.JSONField(help_text='JSON array of coordinate points')),
                ('predicted_object', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('is_correct', models.BooleanField()),
                ('all_probabilities', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(default='64x64_hybrid', max_length=50)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='drawing_app.drawingsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expected_object'], name='drawing_app_expecte_df24f2_idx'), models.Index(fields=['predicted_object'], name='drawing_app_predict_3c3387_idx'), models.Index(fields=['confidence'], name='drawing_app_confide_144b66_idx'), models.Index(fields=['is_correct'], name='drawing_app_is_corr_8dbaaf_idx'), models.Index(fields=['created_at'], name='drawing_app_created_7a946c_idx')],
            },
        ),
    ]
